"""Generate committed static artifacts from the canonical homepage. No runtime build."""
from pathlib import Path
import argparse, json, re
from bs4 import BeautifulSoup
root = Path(__file__).resolve().parent
soup = BeautifulSoup((root/'index.html').read_text(encoding='utf-8'),'html.parser')

def amounts(key):
    return [int(value.replace(',','')) for value in re.findall(r'\$([\d,]+)',soup.select_one('#service-'+key+' strong').get_text())]

prices = dict(onePage=amounts('one-page')[0],business=amounts('business-site')[0],extraLow=amounts('extra-page')[0],extraHigh=amounts('extra-page')[1],care=amounts('care')[0],automation=amounts('automation')[0],pro=amounts('automation-pro')[0])
price_js = '/* Generated by build_site.py from index.html pricing rows. Do not edit. */\n(function () {\n    const prices = Object.freeze('+json.dumps(prices,separators=(',',':'))+');\n    if (typeof module !== "undefined" && module.exports) module.exports = prices;\n    else window.FlexPrices = prices;\n})();\n'

def component(selector):
    fragment = BeautifulSoup(str(soup.select_one(selector)),'html.parser')
    for element in fragment.select('[href],[src]'):
        for attr in ['href','src']:
            value = element.get(attr)
            if not value or re.match(r'^(https?:|mailto:|tel:)',value): continue
            element[attr] = '../'+value
    for link in fragment.select('[data-inquiry]'):
        link['href']='../?inquiry=website#contact'
        del link['data-inquiry']
    return str(fragment)

page = (root/'templates/web-development.html').read_text(encoding='utf-8').replace('<!-- WEBSITE_BUILDS -->',component('.website-builds')).replace('<!-- CASE_STUDY -->',component('.case-study'))
outputs = {'pricing-data.js':price_js,'web-development/index.html':page}
parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
for name,content in outputs.items():
    path=root/name
    if args.check:
        assert path.is_file() and path.read_text(encoding='utf-8')==content, name+' is stale; run python build_site.py'
    else:
        path.parent.mkdir(parents=True,exist_ok=True)
        path.write_text(content,encoding='utf-8',newline='\n')
print('PASS: generated pricing data and web-development page match canonical content' if args.check else 'Generated pricing data and web-development page')
