/* Generated by build_site.py from index.html pricing rows. Do not edit. */
(function () {
    const prices = Object.freeze({"onePage":750,"business":1500,"extraLow":150,"extraHigh":250,"care":49,"automation":99,"pro":179});
    if (typeof module !== "undefined" && module.exports) module.exports = prices;
    else window.FlexPrices = prices;
})();
