const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {featuredFor,dayInDracut,nextCheck}=require('./actias-live.js');
for (let day=0;day<7;day++) assert.ok(featuredFor(day).href.startsWith('#'));
for (const bad of [-1,7,1.5,NaN]) assert.throws(()=>featuredFor(bad));
assert.equal(dayInDracut(new Date('2026-09-26T03:59:59Z')),5);
assert.equal(dayInDracut(new Date('2026-09-26T04:00:00Z')),6);
assert.equal(dayInDracut(new Date('2026-03-08T06:59:59Z')),0);
assert.equal(dayInDracut(new Date('2026-03-08T07:00:00Z')),0);
assert.equal(dayInDracut(new Date('2026-11-01T05:59:59Z')),0);
assert.equal(dayInDracut(new Date('2026-11-01T06:00:00Z')),0);
assert.equal(nextCheck(new Date('2026-09-26T12:34:59Z')).toISOString(),'2026-09-26T12:35:00.000Z');
const elements=new Map(),events={},windowEvents={},timers=new Map();let n=0;
const get=id=> {if (!elements.has(id)) elements.set(id,{value:id==='liveDay'?'today':'',textContent:'',hidden:false,addEventListener(type,fn){this[type]=fn;}});return elements.get(id);};
const document={hidden:false,getElementById:get,addEventListener:(type,fn)=>events[type]=fn};
vm.runInNewContext(fs.readFileSync('actias-live.js','utf8'),{document,window:{addEventListener:(type,fn)=>windowEvents[type]=fn},Intl,Date,setTimeout(fn){timers.set(++n,fn);return n;},clearTimeout(id){timers.delete(id);}});
assert.equal(timers.size,1);
assert.match(get('liveMode').textContent,/LIVE \/ BROWSER/);
get('liveDay').value='1';get('liveDay').change();assert.equal(timers.size,0);
assert.match(get('liveMode').textContent,/SIMULATED/);assert.match(get('liveFeatureTitle').textContent,/workplace/);
get('liveDay').value='today';get('liveDay').change();assert.equal(timers.size,1);
get('livePause').click();assert.equal(timers.size,0);assert.match(get('liveEngine').textContent,/Paused/);
get('livePause').click();assert.equal(timers.size,1);
document.hidden=true;events.visibilitychange();assert.equal(timers.size,0);
document.hidden=false;events.visibilitychange();assert.equal(timers.size,1);
windowEvents.pagehide();assert.equal(timers.size,0);
windowEvents.pageshow();assert.equal(timers.size,1);
console.log('PASS: seven real service rules, Eastern midnight/DST, minute boundary, preview isolation, pause/resume, hidden-page and departure cleanup');
