const assert = require('node:assert/strict');
const {recommend, PRICES} = require('./configurator.js');
const base = {pages:'1', care:'managed', automation:'none', tasks:[], extras:[]};
const get = changes => recommend({...base, ...changes});
assert.equal(get({}).buildPrice, '$750');
assert.equal(get({}).monthly, '$49/month');
for (let n = 2; n <= 5; n++) assert.equal(get({pages:String(n)}).buildPrice, '$1,500');
assert.equal(get({pages:'6'}).buildPrice, '$1,650–$1,750');
assert.equal(get({pages:'10'}).buildPrice, '$2,250–$2,750');
for (const pages of ['custom', '0', '-1', '2.5', '99', '', 'NaN']) assert.equal(get({pages}).buildPrice, 'Custom quote');
assert.equal(get({care:'self'}).monthly, 'No Flex IT monthly plan selected');
assert.equal(get({care:'unsure'}).monthly, 'To discuss');
assert.equal(get({automation:'one'}).monthly, '$99/month');
assert.equal(get({automation:'one', tasks:['Specials','Promotions']}).monthly, '$179/month');
assert.equal(get({automation:'multiple'}).monthly, '$179/month');
assert.equal(get({automation:'custom'}).monthly, 'Custom quote');
assert.equal(get({automation:'one', tasks:['Custom automation']}).monthly, 'Custom quote');
assert.ok(get({automation:'one', care:'self'}).notes.some(n => n.includes('managed technical care')));
assert.ok(get({automation:'unsure'}).notes.some(n => n.includes('before quoting')));
assert.ok(get({automation:'one'}).quotes.includes('Initial automation implementation'));
assert.ok(get({contactForm:true}).quotes.some(n => n.includes('contact form')));
assert.ok(!get({pages:'5',contactForm:true}).quotes.some(n => n.includes('contact form')));
const extras = ['Booking / appointment integration','Ecommerce / online store','Business email setup / migration','SEO beyond included basic search metadata'];
assert.deepEqual(get({extras}).quotes, extras);
assert.equal(get({extras}).buildPrice, '$750'); // No invented add-on total.
assert.equal(get({extras}).monthly, '$49/month');
assert.equal(PRICES.pro,179);
const fs = require('node:fs');
const html = fs.readFileSync(__dirname+'/index.html','utf8');
for (const price of ['$750','$1,500','$150–$250','$49/month','$99/month','$179/month']) assert.ok(html.includes(price),price);
assert.ok(html.includes('form="buildForm"'));
console.log('PASS: published build tiers, extra-page ranges, custom/invalid scope, all care and automation routes, separate add-ons, contact-form scope');
